#include <iostream>
using namespace std;

int main() {
    try {
        throw runtime_error("Something wrong");
    } catch(exception &e) {
        cout << e.what();
    }
}
